# SITE CONFIGURATION
markdown: kramdown
highlighter: rouge

baseurl: "/img"
permalink: /:title/

service_worker: true
future: true

compress_html:
  clippings: all

exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

# COLLECTIONS
collections_dir: docs
collections:
  categories:
    output: true
  tags:
    output: true
  points:
    output: true
  restaurants:
    output: true
  locations:
    output: true

# PLUGINS
plugins:
  - jekyll-avatar
  - jekyll-coffeescript
  - jekyll-commonmark-ghpages
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-remote-theme
  - jekyll-sass-converter
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings

# jekyll-commonmark-ghpages
commonmark:
  options: ["SMART", "FOOTNOTES"]
  extensions: ["strikethrough", "autolink", "table", "tagfilter"]

# jekyll-mentions
jekyll-mentions:
  base_url: https://www.instagram.com

# jekyll-optional-front-matter
include:
  - '_pages'

# jekyll-paginate
paginate:         6
paginate_path:    '/:num'

# jekyll-remote-theme
remote_theme: degustujacaistota/degustujacaistota

# jekyll-seo-tag
title: Degustująca Istota
tagline: >
  “Money, pardon the expression, is like manure. It's not worth a thing unless it's spread around, encouraging young things to grow.”
description: >
  Tester's blog about restaurants. Reviews of a dishes degustations. Ranking of the best restaurants.
url: 'https://degustujacaistota.github.io/'
author: Danuta Irena Żabińska
logo: /assets/img/logo.jpg

social:
  name: Danuta Irena Żabińska
  links:
    - https://www.facebook.com/Degustująca-Istota-309847352979817
    - https://www.instagram.com/degustujacaistota/
    - https://twitter.com/degustujaca
    - https://www.linkedin.com/in/danuta-żabińska-94a74410b
    - https://github.com/degustujacaistota
    - https://plus.google.com/+BenBalter
#    - https://keybase.io/benbalter

# THEME SETTINGS
email: degustujaca.istota@gmail.com
hero_img: main.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg
img_url: 'https://degustujacaistota.github.io/'
img_baseurl: '/img'

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID
google_analytics: UA-143053150-1

#disqus:
#  shortname: janczizikow # to enable comments replace with your_disqus_shortname

# NAVIGATION LINKS
navigation:
  - {name: 'About', link: '/about'}
  - {name: 'Search', link: '/search-jekyll-simple'}
  #  - {name: 'Categories', link: '/categories'}
  - {name: 'Tags', link: '/tags'}
  - {name: 'Locations', link: '/locations'}
  - {name: 'Restaurants', link: '/restaurants'}

# SOCIAL LINKS
social_links:
  rss: rss
  facebook: Degustująca-Istota-309847352979817
  instagram: degustujacaistota
  twitter: degustujaca
  linkedin: danuta-żabińska-94a74410b
  github:  degustujacaistota
  # dribbble: jekyll
  # flickr:   jekyll
  # pinterest: jekyll
  # youtube: jekyll
  # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
  # youtube_channel_name: CloudCannon
  # telegram: jekyll
  # googleplus: +jekyll
  # microdotblog: jekyll
  # keybase: jekyll